import { createContext, useContext, useState } from "react";

const translations = {
  fr: {
    // Navigation
    dashboard: "Tableau de bord",
    transactions: "Transactions",
    categories: "Catégories",
    settings: "Paramètres",
    // KPI labels
    totalRevenue: "Revenus Totaux",
    netProfit: "Bénéfice Net",
    totalMembers: "Membres Actifs",
    churnRate: "Taux de Churn",
    cac: "CAC",
    roas: "ROAS",
    newMembers: "Nouveaux Membres",
    lostMembers: "Membres Perdus",
    marketingSpend: "Budget Marketing",
    adSpend: "Budget Pub",
    // Tabs
    revenue: "Revenus",
    funnel: "Acquisition",
    members: "Membres",
    metrics: "Métriques",
    // Chart labels
    revenueMembers: "Cotisations",
    revenueCoaching: "Coaching",
    expenses: "Dépenses",
    profit: "Bénéfice",
    loyer: "Loyer",
    salaires: "Salaires",
    utilities: "Charges",
    marketing: "Marketing",
    other: "Autres",
    // Transactions
    addTransaction: "Ajouter une transaction",
    date: "Date",
    description: "Description",
    amount: "Montant",
    type: "Type",
    category: "Catégorie",
    subType: "Sous-type",
    actions: "Actions",
    delete: "Supprimer",
    cancel: "Annuler",
    save: "Enregistrer",
    expense: "Dépense",
    revenueType: "Revenu",
    membersType: "Membres",
    coachingType: "Coaching",
    // Misc
    month: "Mois",
    selectMonth: "Sélectionner un mois",
    noData: "Aucune donnée",
    loading: "Chargement...",
    confirmDelete: "Confirmer la suppression",
    deleteWarning: "Cette transaction sera exclue des récurrences futures.",
    excludedTransactions: "Transactions exclues",
    profitMargin: "Marge Nette",
    vsLastMonth: "vs mois préc.",
    seedData: "Charger données démo",
    seeding: "Chargement...",
    totalExpenses: "Dépenses Totales",
    revenueEvolution: "Évolution des Revenus",
    expensesBreakdown: "Répartition des Dépenses",
    memberVsCoaching: "Membres vs Coaching",
    acquisitionFunnel: "Entonnoir d'Acquisition",
    cacEvolution: "Évolution du CAC",
    membersEvolution: "Évolution des Membres",
    churnEvolution: "Taux de Churn",
    roasEvolution: "Évolution du ROAS",
    profitEvolution: "Bénéfice Net",
  },
  en: {
    dashboard: "Dashboard",
    transactions: "Transactions",
    categories: "Categories",
    settings: "Settings",
    totalRevenue: "Total Revenue",
    netProfit: "Net Profit",
    totalMembers: "Active Members",
    churnRate: "Churn Rate",
    cac: "CAC",
    roas: "ROAS",
    newMembers: "New Members",
    lostMembers: "Lost Members",
    marketingSpend: "Marketing Budget",
    adSpend: "Ad Spend",
    revenue: "Revenue",
    funnel: "Acquisition",
    members: "Members",
    metrics: "Metrics",
    revenueMembers: "Memberships",
    revenueCoaching: "Coaching",
    expenses: "Expenses",
    profit: "Profit",
    loyer: "Rent",
    salaires: "Salaries",
    utilities: "Utilities",
    marketing: "Marketing",
    other: "Other",
    addTransaction: "Add Transaction",
    date: "Date",
    description: "Description",
    amount: "Amount",
    type: "Type",
    category: "Category",
    subType: "Sub-type",
    actions: "Actions",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    expense: "Expense",
    revenueType: "Revenue",
    membersType: "Members",
    coachingType: "Coaching",
    month: "Month",
    selectMonth: "Select month",
    noData: "No data",
    loading: "Loading...",
    confirmDelete: "Confirm deletion",
    deleteWarning: "This transaction will be excluded from future recurrences.",
    excludedTransactions: "Excluded Transactions",
    profitMargin: "Net Margin",
    vsLastMonth: "vs prev. month",
    seedData: "Load demo data",
    seeding: "Loading...",
    totalExpenses: "Total Expenses",
    revenueEvolution: "Revenue Evolution",
    expensesBreakdown: "Expenses Breakdown",
    memberVsCoaching: "Members vs Coaching",
    acquisitionFunnel: "Acquisition Funnel",
    cacEvolution: "CAC Evolution",
    membersEvolution: "Members Evolution",
    churnEvolution: "Churn Rate",
    roasEvolution: "ROAS Evolution",
    profitEvolution: "Net Profit",
  },
};

const LanguageContext = createContext({
  lang: "fr",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("fr");
  const t = (key) => translations[lang][key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
